#pragma once
int mpi();
void first_task();
void second_task();
void third_task();
void fourth_task();
void fifth_task();
void sixth_task();
void seventh_task();
void eighth_task();
void ninth_task();
void tenth_task();
void eleventh_task();
void twelveth_task();
void fifteenth_task();